package com.xpertcash.entity;

public enum PermissionType {
    GERER_PRODUITS,
    VENDRE_PRODUITS,
    APPROVISIONNER_STOCK,
    GESTION_FACTURATION,
    GERER_CLIENTS,
    GERER_FOURNISSEURS,
    GERER_UTILISATEURS,
    GERER_BOUTIQUE,
    ACTIVER_BOUTIQUE,
    DESACTIVER_BOUTIQUE,
    COMPTABILITE,
    VOIR_FLUX_COMPTABLE,


    
    /*
    VOIR_FLUX_COMPTABLE,
    GERER_PERSONNEL,
    */
}
